export const getIcon: Record<
  string,
  { icon: string; library: string; color: string; backgroundColor: string }
> = {
  Work: {
    icon: "briefcase",
    library: "FontAwesome",
    color: "#FFFFFF",
    backgroundColor: "#4A4F8C",
  },
  Study: {
    icon: "book",
    library: "FontAwesome",
    color: "#FFFFFF",
    backgroundColor: "#A67C3B",
  },
  Exercise: {
    icon: "dumbbell",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#3D8B75",
  },
  Coding: {
    icon: "code",
    library: "MaterialIcons",
    color: "#FFFFFF",
    backgroundColor: "#4A90E2",
  },
  Music: {
    icon: "music",
    library: "FontAwesome",
    color: "#FFFFFF",
    backgroundColor: "#7B4397",
  },
  Gaming: {
    icon: "gamepad-variant",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#D4145A",
  },
  Learning: {
    icon: "book-open",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#00897B",
  },
  Social: {
    icon: "account-group",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#AB47BC",
  },
  Hobbies: {
    icon: "palette",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#F4511E",
  },
  Meditation: {
    icon: "spa",
    library: "MaterialIcons",
    color: "#FFFFFF",
    backgroundColor: "#6D4C41",
  },
  "Self-Improvement": {
    icon: "trending-up",
    library: "Feather",
    color: "#FFFFFF",
    backgroundColor: "#1E88E5",
  },
  "Food & Cooking": {
    icon: "silverware-fork-knife",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#8D6E63",
  },
  Creativity: {
    icon: "brush",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#5C6BC0",
  },
  Reading: {
    icon: "book",
    library: "FontAwesome",
    color: "#FFFFFF",
    backgroundColor: "#3949AB",
  },
  Writing: {
    icon: "pencil-alt",
    library: "FontAwesome5",
    color: "#FFFFFF",
    backgroundColor: "#039BE5",
  },
  Personal: {
    icon: "user",
    library: "FontAwesome",
    color: "#FFFFFF",
    backgroundColor: "#7E57C2",
  },
  Finance: {
    icon: "finance",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#388E3C",
  },
  Celebration: {
    icon: "party-popper",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#FBC02D",
  },
  Anniversary: {
    icon: "cake-variant",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#EC407A",
  },
  Travel: {
    icon: "airplane",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#0288D1",
  },
  Health: {
    icon: "heart-pulse",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#C2185B",
  },
  Other: {
    icon: "clipboard-list",
    library: "MaterialCommunityIcons",
    color: "#FFFFFF",
    backgroundColor: "#616161",
  },
};
