const productivityQuotes: string[] = [
  "Today is full of possibility.",
  "Every moment is a fresh start.",
  "Progress begins with a single step.",
  "You have everything you need to begin.",
  "Tiny efforts add up to big results.",
  "Use your time to build the life you love.",
  "A focused mind is a powerful thing.",
  "Each day is a new opportunity to grow.",
  "Productivity is your superpower.",
  "Show up, shine bright.",
  "Great things begin with small actions.",
  "Every task completed builds momentum.",
  "You are capable of amazing progress.",
  "Stay present, stay powerful.",
  "Time is your most valuable resource—use it joyfully.",
  "Each hour is a chance to create.",
  "Productivity is self-care with direction.",
  "Organize your time, energize your life.",
  "You’re building something great—keep going.",
  "Invest time in what matters most.",
  "Let your actions reflect your dreams.",
  "Time spent wisely is time spent happily.",
  "You have time for what you make time for.",
  "Celebrate every small win.",
  "Each moment holds progress potential.",
  "You’re already on your way.",
  "Being present is the first step to progress.",
  "You’re growing—one step at a time.",
  "Use your minutes to build miracles.",
  "Purpose fuels productivity.",
  "Every focused minute is a seed for success.",
  "You’re allowed to move forward with grace.",
  "Stay steady, stay strong.",
  "One task at a time, one win at a time.",
  "Every second holds potential.",
  "Time is your canvas—create with it.",
  "You're doing better than you think.",
  "You’re learning and evolving daily.",
  "Keep moving, keep creating.",
  "Use time to lift yourself higher.",
  "Growth lives in the routine.",
  "You are the master of your time.",
  "Choose to use time for joy and purpose.",
  "Focus is your best friend today.",
  "Small steps bring giant rewards.",
  "Give your time to what fuels you.",
  "Do one kind thing for your future self today.",
  "Each task is a step toward your dreams.",
  "Your rhythm, your pace, your power.",
  "Let your schedule reflect your values.",
  "Today’s effort creates tomorrow’s ease.",
  "Your consistency is your strength.",
  "Show up with intention.",
  "Good time use = more peace, more joy.",
  "Time blossoms when used with love.",
  "Trust your pace.",
  "Let your priorities lead the way.",
  "You are progressing, one moment at a time.",
  "Use time to build what you believe in.",
  "There is power in focus.",
  "Choose calm productivity.",
  "Your future self is cheering you on.",
  "Structure creates freedom.",
  "Direction matters more than speed.",
  "Organize time like a gift to yourself.",
  "Let time work in your favor.",
  "Focused time creates fulfilled days.",
  "Today holds beautiful potential.",
  "Productivity is an act of self-respect.",
  "Your focus is your magic.",
  "Time used with joy is time well spent.",
  "Purpose brings peace.",
  "You are capable of focused brilliance.",
  "The next good thing begins now.",
  "Clarity leads to calm progress.",
  "Flow with your tasks, don’t fight them.",
  "Every hour brings new possibility.",
  "Each task is a tiny act of courage.",
  "You’re crafting your best self, daily.",
  "Let time lift, not pressure you.",
  "Your effort plants powerful seeds.",
  "Love the process, not just the results.",
  "Use time with kindness.",
  "A focused you is an unstoppable you.",
  "Prioritize peace and progress.",
  "Celebrate showing up.",
  "Every small effort counts.",
  "Start where you are.",
  "Consistency is your silent power.",
  "Time is your playground—explore it.",
  "Productivity can feel good.",
  "You’ve got this—one task at a time.",
  "Your time is meaningful.",
  "Stay aligned, stay productive.",
  "Your time can shape your dream life.",
  "Focus is a form of self-love.",
  "You’re turning minutes into meaning.",
  "Keep showing up for your goals.",
  "Good things come from good focus.",
  "You own your time—use it beautifully.",
];

export default productivityQuotes;